// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PruebaMoneda5Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void pruebaMoneda5() {
    // Test name: PruebaMoneda 5
    // Step # | name | target | value
    // 1 | open | https://expresscart-testing-xgxnh.ondigitalocean.app/admin/login | 
    driver.get("https://expresscart-testing-xgxnh.ondigitalocean.app/admin/login");
    // 2 | setWindowSize | 1116x608 | 
    driver.manage().window().setSize(new Dimension(1116, 608));
    // 3 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 4 | type | id=email | michelleghblue@gmail.com
    driver.findElement(By.id("email")).sendKeys("michelleghblue@gmail.com");
    // 5 | click | id=password | 
    driver.findElement(By.id("password")).click();
    // 6 | type | id=password | expresscart
    driver.findElement(By.id("password")).sendKeys("expresscart");
    // 7 | sendKeys | id=password | ${KEY_ENTER}
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
    // 8 | click | linkText=General settings | 
    driver.findElement(By.linkText("General settings")).click();
    // 9 | click | name=currencySymbol | 
    driver.findElement(By.name("currencySymbol")).click();
    // 10 | click | name=currencySymbol | 
    driver.findElement(By.name("currencySymbol")).click();
    // 11 | type | name=currencySymbol | .
    driver.findElement(By.name("currencySymbol")).sendKeys(".");
    // 12 | click | id=btnSettingsUpdate | 
    driver.findElement(By.id("btnSettingsUpdate")).click();
    // 13 | assertElementPresent | css=.has-error > .help-block | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".has-error > .help-block"));
      assert(elements.size() > 0);
    }
  }
}
