// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PruebasGeneralSettings2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void pruebasGeneralSettings2() {
    // Test name: Pruebas GeneralSettings 2
    // Step # | name | target | value
    // 1 | open | https://expresscart-testing-xgxnh.ondigitalocean.app/admin/login | 
    driver.get("https://expresscart-testing-xgxnh.ondigitalocean.app/admin/login");
    // 2 | setWindowSize | 1116x608 | 
    driver.manage().window().setSize(new Dimension(1116, 608));
    // 3 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 4 | type | id=email | michelleghblue@gmail.com
    driver.findElement(By.id("email")).sendKeys("michelleghblue@gmail.com");
    // 5 | click | id=password | 
    driver.findElement(By.id("password")).click();
    // 6 | type | id=password | expresscart
    driver.findElement(By.id("password")).sendKeys("expresscart");
    // 7 | click | id=loginForm | 
    driver.findElement(By.id("loginForm")).click();
    // 8 | click | linkText=General settings | 
    driver.findElement(By.linkText("General settings")).click();
    // 9 | click | name=emailAddress | 
    driver.findElement(By.name("emailAddress")).click();
    // 10 | click | name=emailAddress | 
    driver.findElement(By.name("emailAddress")).click();
    // 11 | doubleClick | name=emailAddress | 
    {
      WebElement element = driver.findElement(By.name("emailAddress"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 12 | click | name=emailAddress | 
    driver.findElement(By.name("emailAddress")).click();
    // 13 | click | name=emailAddress | 
    driver.findElement(By.name("emailAddress")).click();
    // 14 | click | css=.col-md-12 | 
    driver.findElement(By.cssSelector(".col-md-12")).click();
    // 15 | doubleClick | css=.col-md-12 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".col-md-12"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 16 | type | name=emailAddress | .
    driver.findElement(By.name("emailAddress")).sendKeys("");
    // 17 | click | name=emailAddress | 
    driver.findElement(By.name("emailAddress")).click();
    // 18 | type | name=emailAddress | hi@@markmoffat.com
    driver.findElement(By.name("emailAddress")).sendKeys("hi@@markmoffat.com");
    // 19 | click | css=.has-error > .help-block | 
    driver.findElement(By.cssSelector(".has-error > .help-block")).click();
    // 20 | click | id=btnSettingsUpdate | 
    driver.findElement(By.id("btnSettingsUpdate")).click();
    // 21 | assertElementPresent | css=.has-error > .help-block | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".has-error > .help-block"));
      assert(elements.size() > 0);
    }
  }
}
